/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'

// Create Virtual Routes

const AuthenticatedConfigLazyImport = createFileRoute(
  '/_authenticated/config',
)()
const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const AuthenticatedSettingsRouteLazyImport = createFileRoute(
  '/_authenticated/settings',
)()
const AuthenticatedUsersIndexLazyImport = createFileRoute(
  '/_authenticated/users/',
)()
const AuthenticatedSettingsIndexLazyImport = createFileRoute(
  '/_authenticated/settings/',
)()
const AuthenticatedHelpCenterIndexLazyImport = createFileRoute(
  '/_authenticated/help-center/',
)()
const AuthenticatedChatsIndexLazyImport = createFileRoute(
  '/_authenticated/chats/',
)()
const AuthenticatedEntityIndexLazyImport = createFileRoute(
  '/_authenticated/$entity/',
)()
const AuthenticatedToolsGraphqlLazyImport = createFileRoute(
  '/_authenticated/tools/graphql',
)()
const AuthenticatedToolsAuditLazyImport = createFileRoute(
  '/_authenticated/tools/audit',
)()
const AuthenticatedStorageSitesLazyImport = createFileRoute(
  '/_authenticated/storage/sites',
)()
const AuthenticatedStorageCloudStoresLazyImport = createFileRoute(
  '/_authenticated/storage/cloud-stores',
)()
const AuthenticatedStorageCertificatesLazyImport = createFileRoute(
  '/_authenticated/storage/certificates',
)()
const AuthenticatedSettingsNotificationsLazyImport = createFileRoute(
  '/_authenticated/settings/notifications',
)()
const AuthenticatedSettingsDisplayLazyImport = createFileRoute(
  '/_authenticated/settings/display',
)()
const AuthenticatedSettingsAppearanceLazyImport = createFileRoute(
  '/_authenticated/settings/appearance',
)()
const AuthenticatedSettingsAccountLazyImport = createFileRoute(
  '/_authenticated/settings/account',
)()
const AuthenticatedDataStreamsLazyImport = createFileRoute(
  '/_authenticated/data/streams',
)()
const AuthenticatedDataIntegrationsLazyImport = createFileRoute(
  '/_authenticated/data/integrations',
)()
const AuthenticatedDataImportLazyImport = createFileRoute(
  '/_authenticated/data/import',
)()
const AuthenticatedDataExportLazyImport = createFileRoute(
  '/_authenticated/data/export',
)()
const AuthenticatedDataExchangesLazyImport = createFileRoute(
  '/_authenticated/data/exchanges',
)()
const AuthenticatedCreateEntityLazyImport = createFileRoute(
  '/_authenticated/create/$entity',
)()
const AuthenticatedCommunicationWebsocketLazyImport = createFileRoute(
  '/_authenticated/communication/websocket',
)()
const AuthenticatedCommunicationOauthLazyImport = createFileRoute(
  '/_authenticated/communication/oauth',
)()
const AuthenticatedCommunicationEmailLazyImport = createFileRoute(
  '/_authenticated/communication/email',
)()
const AuthenticatedAdminUsersLazyImport = createFileRoute(
  '/_authenticated/admin/users',
)()
const AuthenticatedAdminStateMachinesLazyImport = createFileRoute(
  '/_authenticated/admin/state-machines',
)()
const AuthenticatedAdminPermissionsLazyImport = createFileRoute(
  '/_authenticated/admin/permissions',
)()
const AuthenticatedAdminGroupsLazyImport = createFileRoute(
  '/_authenticated/admin/groups',
)()
const AuthenticatedAdminActionsLazyImport = createFileRoute(
  '/_authenticated/admin/actions',
)()
const AuthenticatedEntityReferenceIdIndexLazyImport = createFileRoute(
  '/_authenticated/$entity/$referenceId/',
)()
const AuthenticatedStorageSitesSiteIdLazyImport = createFileRoute(
  '/_authenticated/storage/sites/$siteId',
)()
const AuthenticatedStorageCloudStoresStoreIdLazyImport = createFileRoute(
  '/_authenticated/storage/cloud-stores/$storeId',
)()
const AuthenticatedDataIntegrationsIntegrationIdLazyImport = createFileRoute(
  '/_authenticated/data/integrations/$integrationId',
)()
const AuthenticatedAdminStateMachinesSmdIdLazyImport = createFileRoute(
  '/_authenticated/admin/state-machines/$smdId',
)()
const AuthenticatedAdminActionsActionIdLazyImport = createFileRoute(
  '/_authenticated/admin/actions/$actionId',
)()
const AuthenticatedEntityReferenceIdEditLazyImport = createFileRoute(
  '/_authenticated/$entity/$referenceId/edit',
)()

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedConfigLazyRoute = AuthenticatedConfigLazyImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/config.lazy').then((d) => d.Route),
)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsRouteLazyRoute =
  AuthenticatedSettingsRouteLazyImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/route.lazy').then((d) => d.Route),
  )

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedUsersIndexLazyRoute =
  AuthenticatedUsersIndexLazyImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/users/index.lazy').then((d) => d.Route),
  )

const AuthenticatedSettingsIndexLazyRoute =
  AuthenticatedSettingsIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/index.lazy').then((d) => d.Route),
  )

const AuthenticatedHelpCenterIndexLazyRoute =
  AuthenticatedHelpCenterIndexLazyImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/help-center/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedChatsIndexLazyRoute =
  AuthenticatedChatsIndexLazyImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/chats/index.lazy').then((d) => d.Route),
  )

const AuthenticatedEntityIndexLazyRoute =
  AuthenticatedEntityIndexLazyImport.update({
    id: '/$entity/',
    path: '/$entity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/$entity/index.lazy').then((d) => d.Route),
  )

const AuthenticatedToolsGraphqlLazyRoute =
  AuthenticatedToolsGraphqlLazyImport.update({
    id: '/tools/graphql',
    path: '/tools/graphql',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tools/graphql.lazy').then((d) => d.Route),
  )

const AuthenticatedToolsAuditLazyRoute =
  AuthenticatedToolsAuditLazyImport.update({
    id: '/tools/audit',
    path: '/tools/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/tools/audit.lazy').then((d) => d.Route),
  )

const AuthenticatedStorageSitesLazyRoute =
  AuthenticatedStorageSitesLazyImport.update({
    id: '/storage/sites',
    path: '/storage/sites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/storage/sites.lazy').then((d) => d.Route),
  )

const AuthenticatedStorageCloudStoresLazyRoute =
  AuthenticatedStorageCloudStoresLazyImport.update({
    id: '/storage/cloud-stores',
    path: '/storage/cloud-stores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/storage/cloud-stores.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStorageCertificatesLazyRoute =
  AuthenticatedStorageCertificatesLazyImport.update({
    id: '/storage/certificates',
    path: '/storage/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/storage/certificates.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsNotificationsLazyRoute =
  AuthenticatedSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/notifications.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsDisplayLazyRoute =
  AuthenticatedSettingsDisplayLazyImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/display.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAppearanceLazyRoute =
  AuthenticatedSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/appearance.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedSettingsAccountLazyRoute =
  AuthenticatedSettingsAccountLazyImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/settings/account.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDataStreamsLazyRoute =
  AuthenticatedDataStreamsLazyImport.update({
    id: '/data/streams',
    path: '/data/streams',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/data/streams.lazy').then((d) => d.Route),
  )

const AuthenticatedDataIntegrationsLazyRoute =
  AuthenticatedDataIntegrationsLazyImport.update({
    id: '/data/integrations',
    path: '/data/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/data/integrations.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDataImportLazyRoute =
  AuthenticatedDataImportLazyImport.update({
    id: '/data/import',
    path: '/data/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/data/import.lazy').then((d) => d.Route),
  )

const AuthenticatedDataExportLazyRoute =
  AuthenticatedDataExportLazyImport.update({
    id: '/data/export',
    path: '/data/export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/data/export.lazy').then((d) => d.Route),
  )

const AuthenticatedDataExchangesLazyRoute =
  AuthenticatedDataExchangesLazyImport.update({
    id: '/data/exchanges',
    path: '/data/exchanges',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/data/exchanges.lazy').then((d) => d.Route),
  )

const AuthenticatedCreateEntityLazyRoute =
  AuthenticatedCreateEntityLazyImport.update({
    id: '/create/$entity',
    path: '/create/$entity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/create/$entity.lazy').then((d) => d.Route),
  )

const AuthenticatedCommunicationWebsocketLazyRoute =
  AuthenticatedCommunicationWebsocketLazyImport.update({
    id: '/communication/websocket',
    path: '/communication/websocket',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/communication/websocket.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCommunicationOauthLazyRoute =
  AuthenticatedCommunicationOauthLazyImport.update({
    id: '/communication/oauth',
    path: '/communication/oauth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/communication/oauth.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedCommunicationEmailLazyRoute =
  AuthenticatedCommunicationEmailLazyImport.update({
    id: '/communication/email',
    path: '/communication/email',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/communication/email.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminUsersLazyRoute =
  AuthenticatedAdminUsersLazyImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/users.lazy').then((d) => d.Route),
  )

const AuthenticatedAdminStateMachinesLazyRoute =
  AuthenticatedAdminStateMachinesLazyImport.update({
    id: '/admin/state-machines',
    path: '/admin/state-machines',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/state-machines.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminPermissionsLazyRoute =
  AuthenticatedAdminPermissionsLazyImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/permissions.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminGroupsLazyRoute =
  AuthenticatedAdminGroupsLazyImport.update({
    id: '/admin/groups',
    path: '/admin/groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/groups.lazy').then((d) => d.Route),
  )

const AuthenticatedAdminActionsLazyRoute =
  AuthenticatedAdminActionsLazyImport.update({
    id: '/admin/actions',
    path: '/admin/actions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/actions.lazy').then((d) => d.Route),
  )

const AuthenticatedEntityReferenceIdIndexLazyRoute =
  AuthenticatedEntityReferenceIdIndexLazyImport.update({
    id: '/$entity/$referenceId/',
    path: '/$entity/$referenceId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/$entity/$referenceId/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStorageSitesSiteIdLazyRoute =
  AuthenticatedStorageSitesSiteIdLazyImport.update({
    id: '/$siteId',
    path: '/$siteId',
    getParentRoute: () => AuthenticatedStorageSitesLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/storage/sites.$siteId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedStorageCloudStoresStoreIdLazyRoute =
  AuthenticatedStorageCloudStoresStoreIdLazyImport.update({
    id: '/$storeId',
    path: '/$storeId',
    getParentRoute: () => AuthenticatedStorageCloudStoresLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/storage/cloud-stores.$storeId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedDataIntegrationsIntegrationIdLazyRoute =
  AuthenticatedDataIntegrationsIntegrationIdLazyImport.update({
    id: '/$integrationId',
    path: '/$integrationId',
    getParentRoute: () => AuthenticatedDataIntegrationsLazyRoute,
  } as any).lazy(() =>
    import(
      './routes/_authenticated/data/integrations.$integrationId.lazy'
    ).then((d) => d.Route),
  )

const AuthenticatedAdminStateMachinesSmdIdLazyRoute =
  AuthenticatedAdminStateMachinesSmdIdLazyImport.update({
    id: '/$smdId',
    path: '/$smdId',
    getParentRoute: () => AuthenticatedAdminStateMachinesLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/state-machines.$smdId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedAdminActionsActionIdLazyRoute =
  AuthenticatedAdminActionsActionIdLazyImport.update({
    id: '/$actionId',
    path: '/$actionId',
    getParentRoute: () => AuthenticatedAdminActionsLazyRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/admin/actions.$actionId.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthenticatedEntityReferenceIdEditLazyRoute =
  AuthenticatedEntityReferenceIdEditLazyImport.update({
    id: '/$entity/$referenceId/edit',
    path: '/$entity/$referenceId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/$entity/$referenceId/edit.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/actions': {
      id: '/_authenticated/admin/actions'
      path: '/admin/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AuthenticatedAdminActionsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/groups': {
      id: '/_authenticated/admin/groups'
      path: '/admin/groups'
      fullPath: '/admin/groups'
      preLoaderRoute: typeof AuthenticatedAdminGroupsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/state-machines': {
      id: '/_authenticated/admin/state-machines'
      path: '/admin/state-machines'
      fullPath: '/admin/state-machines'
      preLoaderRoute: typeof AuthenticatedAdminStateMachinesLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/communication/email': {
      id: '/_authenticated/communication/email'
      path: '/communication/email'
      fullPath: '/communication/email'
      preLoaderRoute: typeof AuthenticatedCommunicationEmailLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/communication/oauth': {
      id: '/_authenticated/communication/oauth'
      path: '/communication/oauth'
      fullPath: '/communication/oauth'
      preLoaderRoute: typeof AuthenticatedCommunicationOauthLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/communication/websocket': {
      id: '/_authenticated/communication/websocket'
      path: '/communication/websocket'
      fullPath: '/communication/websocket'
      preLoaderRoute: typeof AuthenticatedCommunicationWebsocketLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/create/$entity': {
      id: '/_authenticated/create/$entity'
      path: '/create/$entity'
      fullPath: '/create/$entity'
      preLoaderRoute: typeof AuthenticatedCreateEntityLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/data/exchanges': {
      id: '/_authenticated/data/exchanges'
      path: '/data/exchanges'
      fullPath: '/data/exchanges'
      preLoaderRoute: typeof AuthenticatedDataExchangesLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/data/export': {
      id: '/_authenticated/data/export'
      path: '/data/export'
      fullPath: '/data/export'
      preLoaderRoute: typeof AuthenticatedDataExportLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/data/import': {
      id: '/_authenticated/data/import'
      path: '/data/import'
      fullPath: '/data/import'
      preLoaderRoute: typeof AuthenticatedDataImportLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/data/integrations': {
      id: '/_authenticated/data/integrations'
      path: '/data/integrations'
      fullPath: '/data/integrations'
      preLoaderRoute: typeof AuthenticatedDataIntegrationsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/data/streams': {
      id: '/_authenticated/data/streams'
      path: '/data/streams'
      fullPath: '/data/streams'
      preLoaderRoute: typeof AuthenticatedDataStreamsLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/storage/certificates': {
      id: '/_authenticated/storage/certificates'
      path: '/storage/certificates'
      fullPath: '/storage/certificates'
      preLoaderRoute: typeof AuthenticatedStorageCertificatesLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/storage/cloud-stores': {
      id: '/_authenticated/storage/cloud-stores'
      path: '/storage/cloud-stores'
      fullPath: '/storage/cloud-stores'
      preLoaderRoute: typeof AuthenticatedStorageCloudStoresLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/storage/sites': {
      id: '/_authenticated/storage/sites'
      path: '/storage/sites'
      fullPath: '/storage/sites'
      preLoaderRoute: typeof AuthenticatedStorageSitesLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tools/audit': {
      id: '/_authenticated/tools/audit'
      path: '/tools/audit'
      fullPath: '/tools/audit'
      preLoaderRoute: typeof AuthenticatedToolsAuditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/tools/graphql': {
      id: '/_authenticated/tools/graphql'
      path: '/tools/graphql'
      fullPath: '/tools/graphql'
      preLoaderRoute: typeof AuthenticatedToolsGraphqlLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/$entity/': {
      id: '/_authenticated/$entity/'
      path: '/$entity'
      fullPath: '/$entity'
      preLoaderRoute: typeof AuthenticatedEntityIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexLazyImport
      parentRoute: typeof AuthenticatedSettingsRouteLazyImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/$entity/$referenceId/edit': {
      id: '/_authenticated/$entity/$referenceId/edit'
      path: '/$entity/$referenceId/edit'
      fullPath: '/$entity/$referenceId/edit'
      preLoaderRoute: typeof AuthenticatedEntityReferenceIdEditLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/admin/actions/$actionId': {
      id: '/_authenticated/admin/actions/$actionId'
      path: '/$actionId'
      fullPath: '/admin/actions/$actionId'
      preLoaderRoute: typeof AuthenticatedAdminActionsActionIdLazyImport
      parentRoute: typeof AuthenticatedAdminActionsLazyImport
    }
    '/_authenticated/admin/state-machines/$smdId': {
      id: '/_authenticated/admin/state-machines/$smdId'
      path: '/$smdId'
      fullPath: '/admin/state-machines/$smdId'
      preLoaderRoute: typeof AuthenticatedAdminStateMachinesSmdIdLazyImport
      parentRoute: typeof AuthenticatedAdminStateMachinesLazyImport
    }
    '/_authenticated/data/integrations/$integrationId': {
      id: '/_authenticated/data/integrations/$integrationId'
      path: '/$integrationId'
      fullPath: '/data/integrations/$integrationId'
      preLoaderRoute: typeof AuthenticatedDataIntegrationsIntegrationIdLazyImport
      parentRoute: typeof AuthenticatedDataIntegrationsLazyImport
    }
    '/_authenticated/storage/cloud-stores/$storeId': {
      id: '/_authenticated/storage/cloud-stores/$storeId'
      path: '/$storeId'
      fullPath: '/storage/cloud-stores/$storeId'
      preLoaderRoute: typeof AuthenticatedStorageCloudStoresStoreIdLazyImport
      parentRoute: typeof AuthenticatedStorageCloudStoresLazyImport
    }
    '/_authenticated/storage/sites/$siteId': {
      id: '/_authenticated/storage/sites/$siteId'
      path: '/$siteId'
      fullPath: '/storage/sites/$siteId'
      preLoaderRoute: typeof AuthenticatedStorageSitesSiteIdLazyImport
      parentRoute: typeof AuthenticatedStorageSitesLazyImport
    }
    '/_authenticated/$entity/$referenceId/': {
      id: '/_authenticated/$entity/$referenceId/'
      path: '/$entity/$referenceId'
      fullPath: '/$entity/$referenceId'
      preLoaderRoute: typeof AuthenticatedEntityReferenceIdIndexLazyImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedSettingsRouteLazyRouteChildren {
  AuthenticatedSettingsAccountLazyRoute: typeof AuthenticatedSettingsAccountLazyRoute
  AuthenticatedSettingsAppearanceLazyRoute: typeof AuthenticatedSettingsAppearanceLazyRoute
  AuthenticatedSettingsDisplayLazyRoute: typeof AuthenticatedSettingsDisplayLazyRoute
  AuthenticatedSettingsNotificationsLazyRoute: typeof AuthenticatedSettingsNotificationsLazyRoute
  AuthenticatedSettingsIndexLazyRoute: typeof AuthenticatedSettingsIndexLazyRoute
}

const AuthenticatedSettingsRouteLazyRouteChildren: AuthenticatedSettingsRouteLazyRouteChildren =
  {
    AuthenticatedSettingsAccountLazyRoute:
      AuthenticatedSettingsAccountLazyRoute,
    AuthenticatedSettingsAppearanceLazyRoute:
      AuthenticatedSettingsAppearanceLazyRoute,
    AuthenticatedSettingsDisplayLazyRoute:
      AuthenticatedSettingsDisplayLazyRoute,
    AuthenticatedSettingsNotificationsLazyRoute:
      AuthenticatedSettingsNotificationsLazyRoute,
    AuthenticatedSettingsIndexLazyRoute: AuthenticatedSettingsIndexLazyRoute,
  }

const AuthenticatedSettingsRouteLazyRouteWithChildren =
  AuthenticatedSettingsRouteLazyRoute._addFileChildren(
    AuthenticatedSettingsRouteLazyRouteChildren,
  )

interface AuthenticatedAdminActionsLazyRouteChildren {
  AuthenticatedAdminActionsActionIdLazyRoute: typeof AuthenticatedAdminActionsActionIdLazyRoute
}

const AuthenticatedAdminActionsLazyRouteChildren: AuthenticatedAdminActionsLazyRouteChildren =
  {
    AuthenticatedAdminActionsActionIdLazyRoute:
      AuthenticatedAdminActionsActionIdLazyRoute,
  }

const AuthenticatedAdminActionsLazyRouteWithChildren =
  AuthenticatedAdminActionsLazyRoute._addFileChildren(
    AuthenticatedAdminActionsLazyRouteChildren,
  )

interface AuthenticatedAdminStateMachinesLazyRouteChildren {
  AuthenticatedAdminStateMachinesSmdIdLazyRoute: typeof AuthenticatedAdminStateMachinesSmdIdLazyRoute
}

const AuthenticatedAdminStateMachinesLazyRouteChildren: AuthenticatedAdminStateMachinesLazyRouteChildren =
  {
    AuthenticatedAdminStateMachinesSmdIdLazyRoute:
      AuthenticatedAdminStateMachinesSmdIdLazyRoute,
  }

const AuthenticatedAdminStateMachinesLazyRouteWithChildren =
  AuthenticatedAdminStateMachinesLazyRoute._addFileChildren(
    AuthenticatedAdminStateMachinesLazyRouteChildren,
  )

interface AuthenticatedDataIntegrationsLazyRouteChildren {
  AuthenticatedDataIntegrationsIntegrationIdLazyRoute: typeof AuthenticatedDataIntegrationsIntegrationIdLazyRoute
}

const AuthenticatedDataIntegrationsLazyRouteChildren: AuthenticatedDataIntegrationsLazyRouteChildren =
  {
    AuthenticatedDataIntegrationsIntegrationIdLazyRoute:
      AuthenticatedDataIntegrationsIntegrationIdLazyRoute,
  }

const AuthenticatedDataIntegrationsLazyRouteWithChildren =
  AuthenticatedDataIntegrationsLazyRoute._addFileChildren(
    AuthenticatedDataIntegrationsLazyRouteChildren,
  )

interface AuthenticatedStorageCloudStoresLazyRouteChildren {
  AuthenticatedStorageCloudStoresStoreIdLazyRoute: typeof AuthenticatedStorageCloudStoresStoreIdLazyRoute
}

const AuthenticatedStorageCloudStoresLazyRouteChildren: AuthenticatedStorageCloudStoresLazyRouteChildren =
  {
    AuthenticatedStorageCloudStoresStoreIdLazyRoute:
      AuthenticatedStorageCloudStoresStoreIdLazyRoute,
  }

const AuthenticatedStorageCloudStoresLazyRouteWithChildren =
  AuthenticatedStorageCloudStoresLazyRoute._addFileChildren(
    AuthenticatedStorageCloudStoresLazyRouteChildren,
  )

interface AuthenticatedStorageSitesLazyRouteChildren {
  AuthenticatedStorageSitesSiteIdLazyRoute: typeof AuthenticatedStorageSitesSiteIdLazyRoute
}

const AuthenticatedStorageSitesLazyRouteChildren: AuthenticatedStorageSitesLazyRouteChildren =
  {
    AuthenticatedStorageSitesSiteIdLazyRoute:
      AuthenticatedStorageSitesSiteIdLazyRoute,
  }

const AuthenticatedStorageSitesLazyRouteWithChildren =
  AuthenticatedStorageSitesLazyRoute._addFileChildren(
    AuthenticatedStorageSitesLazyRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteLazyRoute: typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  AuthenticatedConfigLazyRoute: typeof AuthenticatedConfigLazyRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminActionsLazyRoute: typeof AuthenticatedAdminActionsLazyRouteWithChildren
  AuthenticatedAdminGroupsLazyRoute: typeof AuthenticatedAdminGroupsLazyRoute
  AuthenticatedAdminPermissionsLazyRoute: typeof AuthenticatedAdminPermissionsLazyRoute
  AuthenticatedAdminStateMachinesLazyRoute: typeof AuthenticatedAdminStateMachinesLazyRouteWithChildren
  AuthenticatedAdminUsersLazyRoute: typeof AuthenticatedAdminUsersLazyRoute
  AuthenticatedCommunicationEmailLazyRoute: typeof AuthenticatedCommunicationEmailLazyRoute
  AuthenticatedCommunicationOauthLazyRoute: typeof AuthenticatedCommunicationOauthLazyRoute
  AuthenticatedCommunicationWebsocketLazyRoute: typeof AuthenticatedCommunicationWebsocketLazyRoute
  AuthenticatedCreateEntityLazyRoute: typeof AuthenticatedCreateEntityLazyRoute
  AuthenticatedDataExchangesLazyRoute: typeof AuthenticatedDataExchangesLazyRoute
  AuthenticatedDataExportLazyRoute: typeof AuthenticatedDataExportLazyRoute
  AuthenticatedDataImportLazyRoute: typeof AuthenticatedDataImportLazyRoute
  AuthenticatedDataIntegrationsLazyRoute: typeof AuthenticatedDataIntegrationsLazyRouteWithChildren
  AuthenticatedDataStreamsLazyRoute: typeof AuthenticatedDataStreamsLazyRoute
  AuthenticatedStorageCertificatesLazyRoute: typeof AuthenticatedStorageCertificatesLazyRoute
  AuthenticatedStorageCloudStoresLazyRoute: typeof AuthenticatedStorageCloudStoresLazyRouteWithChildren
  AuthenticatedStorageSitesLazyRoute: typeof AuthenticatedStorageSitesLazyRouteWithChildren
  AuthenticatedToolsAuditLazyRoute: typeof AuthenticatedToolsAuditLazyRoute
  AuthenticatedToolsGraphqlLazyRoute: typeof AuthenticatedToolsGraphqlLazyRoute
  AuthenticatedEntityIndexLazyRoute: typeof AuthenticatedEntityIndexLazyRoute
  AuthenticatedChatsIndexLazyRoute: typeof AuthenticatedChatsIndexLazyRoute
  AuthenticatedHelpCenterIndexLazyRoute: typeof AuthenticatedHelpCenterIndexLazyRoute
  AuthenticatedUsersIndexLazyRoute: typeof AuthenticatedUsersIndexLazyRoute
  AuthenticatedEntityReferenceIdEditLazyRoute: typeof AuthenticatedEntityReferenceIdEditLazyRoute
  AuthenticatedEntityReferenceIdIndexLazyRoute: typeof AuthenticatedEntityReferenceIdIndexLazyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteLazyRoute:
    AuthenticatedSettingsRouteLazyRouteWithChildren,
  AuthenticatedConfigLazyRoute: AuthenticatedConfigLazyRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminActionsLazyRoute:
    AuthenticatedAdminActionsLazyRouteWithChildren,
  AuthenticatedAdminGroupsLazyRoute: AuthenticatedAdminGroupsLazyRoute,
  AuthenticatedAdminPermissionsLazyRoute:
    AuthenticatedAdminPermissionsLazyRoute,
  AuthenticatedAdminStateMachinesLazyRoute:
    AuthenticatedAdminStateMachinesLazyRouteWithChildren,
  AuthenticatedAdminUsersLazyRoute: AuthenticatedAdminUsersLazyRoute,
  AuthenticatedCommunicationEmailLazyRoute:
    AuthenticatedCommunicationEmailLazyRoute,
  AuthenticatedCommunicationOauthLazyRoute:
    AuthenticatedCommunicationOauthLazyRoute,
  AuthenticatedCommunicationWebsocketLazyRoute:
    AuthenticatedCommunicationWebsocketLazyRoute,
  AuthenticatedCreateEntityLazyRoute: AuthenticatedCreateEntityLazyRoute,
  AuthenticatedDataExchangesLazyRoute: AuthenticatedDataExchangesLazyRoute,
  AuthenticatedDataExportLazyRoute: AuthenticatedDataExportLazyRoute,
  AuthenticatedDataImportLazyRoute: AuthenticatedDataImportLazyRoute,
  AuthenticatedDataIntegrationsLazyRoute:
    AuthenticatedDataIntegrationsLazyRouteWithChildren,
  AuthenticatedDataStreamsLazyRoute: AuthenticatedDataStreamsLazyRoute,
  AuthenticatedStorageCertificatesLazyRoute:
    AuthenticatedStorageCertificatesLazyRoute,
  AuthenticatedStorageCloudStoresLazyRoute:
    AuthenticatedStorageCloudStoresLazyRouteWithChildren,
  AuthenticatedStorageSitesLazyRoute:
    AuthenticatedStorageSitesLazyRouteWithChildren,
  AuthenticatedToolsAuditLazyRoute: AuthenticatedToolsAuditLazyRoute,
  AuthenticatedToolsGraphqlLazyRoute: AuthenticatedToolsGraphqlLazyRoute,
  AuthenticatedEntityIndexLazyRoute: AuthenticatedEntityIndexLazyRoute,
  AuthenticatedChatsIndexLazyRoute: AuthenticatedChatsIndexLazyRoute,
  AuthenticatedHelpCenterIndexLazyRoute: AuthenticatedHelpCenterIndexLazyRoute,
  AuthenticatedUsersIndexLazyRoute: AuthenticatedUsersIndexLazyRoute,
  AuthenticatedEntityReferenceIdEditLazyRoute:
    AuthenticatedEntityReferenceIdEditLazyRoute,
  AuthenticatedEntityReferenceIdIndexLazyRoute:
    AuthenticatedEntityReferenceIdIndexLazyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/config': typeof AuthenticatedConfigLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/actions': typeof AuthenticatedAdminActionsLazyRouteWithChildren
  '/admin/groups': typeof AuthenticatedAdminGroupsLazyRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsLazyRoute
  '/admin/state-machines': typeof AuthenticatedAdminStateMachinesLazyRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/communication/email': typeof AuthenticatedCommunicationEmailLazyRoute
  '/communication/oauth': typeof AuthenticatedCommunicationOauthLazyRoute
  '/communication/websocket': typeof AuthenticatedCommunicationWebsocketLazyRoute
  '/create/$entity': typeof AuthenticatedCreateEntityLazyRoute
  '/data/exchanges': typeof AuthenticatedDataExchangesLazyRoute
  '/data/export': typeof AuthenticatedDataExportLazyRoute
  '/data/import': typeof AuthenticatedDataImportLazyRoute
  '/data/integrations': typeof AuthenticatedDataIntegrationsLazyRouteWithChildren
  '/data/streams': typeof AuthenticatedDataStreamsLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/storage/certificates': typeof AuthenticatedStorageCertificatesLazyRoute
  '/storage/cloud-stores': typeof AuthenticatedStorageCloudStoresLazyRouteWithChildren
  '/storage/sites': typeof AuthenticatedStorageSitesLazyRouteWithChildren
  '/tools/audit': typeof AuthenticatedToolsAuditLazyRoute
  '/tools/graphql': typeof AuthenticatedToolsGraphqlLazyRoute
  '/$entity': typeof AuthenticatedEntityIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/$entity/$referenceId/edit': typeof AuthenticatedEntityReferenceIdEditLazyRoute
  '/admin/actions/$actionId': typeof AuthenticatedAdminActionsActionIdLazyRoute
  '/admin/state-machines/$smdId': typeof AuthenticatedAdminStateMachinesSmdIdLazyRoute
  '/data/integrations/$integrationId': typeof AuthenticatedDataIntegrationsIntegrationIdLazyRoute
  '/storage/cloud-stores/$storeId': typeof AuthenticatedStorageCloudStoresStoreIdLazyRoute
  '/storage/sites/$siteId': typeof AuthenticatedStorageSitesSiteIdLazyRoute
  '/$entity/$referenceId': typeof AuthenticatedEntityReferenceIdIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/config': typeof AuthenticatedConfigLazyRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/actions': typeof AuthenticatedAdminActionsLazyRouteWithChildren
  '/admin/groups': typeof AuthenticatedAdminGroupsLazyRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsLazyRoute
  '/admin/state-machines': typeof AuthenticatedAdminStateMachinesLazyRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/communication/email': typeof AuthenticatedCommunicationEmailLazyRoute
  '/communication/oauth': typeof AuthenticatedCommunicationOauthLazyRoute
  '/communication/websocket': typeof AuthenticatedCommunicationWebsocketLazyRoute
  '/create/$entity': typeof AuthenticatedCreateEntityLazyRoute
  '/data/exchanges': typeof AuthenticatedDataExchangesLazyRoute
  '/data/export': typeof AuthenticatedDataExportLazyRoute
  '/data/import': typeof AuthenticatedDataImportLazyRoute
  '/data/integrations': typeof AuthenticatedDataIntegrationsLazyRouteWithChildren
  '/data/streams': typeof AuthenticatedDataStreamsLazyRoute
  '/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/storage/certificates': typeof AuthenticatedStorageCertificatesLazyRoute
  '/storage/cloud-stores': typeof AuthenticatedStorageCloudStoresLazyRouteWithChildren
  '/storage/sites': typeof AuthenticatedStorageSitesLazyRouteWithChildren
  '/tools/audit': typeof AuthenticatedToolsAuditLazyRoute
  '/tools/graphql': typeof AuthenticatedToolsGraphqlLazyRoute
  '/$entity': typeof AuthenticatedEntityIndexLazyRoute
  '/chats': typeof AuthenticatedChatsIndexLazyRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/settings': typeof AuthenticatedSettingsIndexLazyRoute
  '/users': typeof AuthenticatedUsersIndexLazyRoute
  '/$entity/$referenceId/edit': typeof AuthenticatedEntityReferenceIdEditLazyRoute
  '/admin/actions/$actionId': typeof AuthenticatedAdminActionsActionIdLazyRoute
  '/admin/state-machines/$smdId': typeof AuthenticatedAdminStateMachinesSmdIdLazyRoute
  '/data/integrations/$integrationId': typeof AuthenticatedDataIntegrationsIntegrationIdLazyRoute
  '/storage/cloud-stores/$storeId': typeof AuthenticatedStorageCloudStoresStoreIdLazyRoute
  '/storage/sites/$siteId': typeof AuthenticatedStorageSitesSiteIdLazyRoute
  '/$entity/$referenceId': typeof AuthenticatedEntityReferenceIdIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_authenticated/config': typeof AuthenticatedConfigLazyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/actions': typeof AuthenticatedAdminActionsLazyRouteWithChildren
  '/_authenticated/admin/groups': typeof AuthenticatedAdminGroupsLazyRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsLazyRoute
  '/_authenticated/admin/state-machines': typeof AuthenticatedAdminStateMachinesLazyRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersLazyRoute
  '/_authenticated/communication/email': typeof AuthenticatedCommunicationEmailLazyRoute
  '/_authenticated/communication/oauth': typeof AuthenticatedCommunicationOauthLazyRoute
  '/_authenticated/communication/websocket': typeof AuthenticatedCommunicationWebsocketLazyRoute
  '/_authenticated/create/$entity': typeof AuthenticatedCreateEntityLazyRoute
  '/_authenticated/data/exchanges': typeof AuthenticatedDataExchangesLazyRoute
  '/_authenticated/data/export': typeof AuthenticatedDataExportLazyRoute
  '/_authenticated/data/import': typeof AuthenticatedDataImportLazyRoute
  '/_authenticated/data/integrations': typeof AuthenticatedDataIntegrationsLazyRouteWithChildren
  '/_authenticated/data/streams': typeof AuthenticatedDataStreamsLazyRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountLazyRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceLazyRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayLazyRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsLazyRoute
  '/_authenticated/storage/certificates': typeof AuthenticatedStorageCertificatesLazyRoute
  '/_authenticated/storage/cloud-stores': typeof AuthenticatedStorageCloudStoresLazyRouteWithChildren
  '/_authenticated/storage/sites': typeof AuthenticatedStorageSitesLazyRouteWithChildren
  '/_authenticated/tools/audit': typeof AuthenticatedToolsAuditLazyRoute
  '/_authenticated/tools/graphql': typeof AuthenticatedToolsGraphqlLazyRoute
  '/_authenticated/$entity/': typeof AuthenticatedEntityIndexLazyRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexLazyRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexLazyRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexLazyRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexLazyRoute
  '/_authenticated/$entity/$referenceId/edit': typeof AuthenticatedEntityReferenceIdEditLazyRoute
  '/_authenticated/admin/actions/$actionId': typeof AuthenticatedAdminActionsActionIdLazyRoute
  '/_authenticated/admin/state-machines/$smdId': typeof AuthenticatedAdminStateMachinesSmdIdLazyRoute
  '/_authenticated/data/integrations/$integrationId': typeof AuthenticatedDataIntegrationsIntegrationIdLazyRoute
  '/_authenticated/storage/cloud-stores/$storeId': typeof AuthenticatedStorageCloudStoresStoreIdLazyRoute
  '/_authenticated/storage/sites/$siteId': typeof AuthenticatedStorageSitesSiteIdLazyRoute
  '/_authenticated/$entity/$referenceId/': typeof AuthenticatedEntityReferenceIdIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/settings'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/config'
    | '/'
    | '/admin/actions'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/state-machines'
    | '/admin/users'
    | '/communication/email'
    | '/communication/oauth'
    | '/communication/websocket'
    | '/create/$entity'
    | '/data/exchanges'
    | '/data/export'
    | '/data/import'
    | '/data/integrations'
    | '/data/streams'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/storage/certificates'
    | '/storage/cloud-stores'
    | '/storage/sites'
    | '/tools/audit'
    | '/tools/graphql'
    | '/$entity'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/users'
    | '/$entity/$referenceId/edit'
    | '/admin/actions/$actionId'
    | '/admin/state-machines/$smdId'
    | '/data/integrations/$integrationId'
    | '/storage/cloud-stores/$storeId'
    | '/storage/sites/$siteId'
    | '/$entity/$referenceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/config'
    | '/'
    | '/admin/actions'
    | '/admin/groups'
    | '/admin/permissions'
    | '/admin/state-machines'
    | '/admin/users'
    | '/communication/email'
    | '/communication/oauth'
    | '/communication/websocket'
    | '/create/$entity'
    | '/data/exchanges'
    | '/data/export'
    | '/data/import'
    | '/data/integrations'
    | '/data/streams'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/storage/certificates'
    | '/storage/cloud-stores'
    | '/storage/sites'
    | '/tools/audit'
    | '/tools/graphql'
    | '/$entity'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/users'
    | '/$entity/$referenceId/edit'
    | '/admin/actions/$actionId'
    | '/admin/state-machines/$smdId'
    | '/data/integrations/$integrationId'
    | '/storage/cloud-stores/$storeId'
    | '/storage/sites/$siteId'
    | '/$entity/$referenceId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/config'
    | '/_authenticated/'
    | '/_authenticated/admin/actions'
    | '/_authenticated/admin/groups'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/state-machines'
    | '/_authenticated/admin/users'
    | '/_authenticated/communication/email'
    | '/_authenticated/communication/oauth'
    | '/_authenticated/communication/websocket'
    | '/_authenticated/create/$entity'
    | '/_authenticated/data/exchanges'
    | '/_authenticated/data/export'
    | '/_authenticated/data/import'
    | '/_authenticated/data/integrations'
    | '/_authenticated/data/streams'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/storage/certificates'
    | '/_authenticated/storage/cloud-stores'
    | '/_authenticated/storage/sites'
    | '/_authenticated/tools/audit'
    | '/_authenticated/tools/graphql'
    | '/_authenticated/$entity/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/$entity/$referenceId/edit'
    | '/_authenticated/admin/actions/$actionId'
    | '/_authenticated/admin/state-machines/$smdId'
    | '/_authenticated/data/integrations/$integrationId'
    | '/_authenticated/storage/cloud-stores/$storeId'
    | '/_authenticated/storage/sites/$siteId'
    | '/_authenticated/$entity/$referenceId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/settings",
        "/_authenticated/config",
        "/_authenticated/",
        "/_authenticated/admin/actions",
        "/_authenticated/admin/groups",
        "/_authenticated/admin/permissions",
        "/_authenticated/admin/state-machines",
        "/_authenticated/admin/users",
        "/_authenticated/communication/email",
        "/_authenticated/communication/oauth",
        "/_authenticated/communication/websocket",
        "/_authenticated/create/$entity",
        "/_authenticated/data/exchanges",
        "/_authenticated/data/export",
        "/_authenticated/data/import",
        "/_authenticated/data/integrations",
        "/_authenticated/data/streams",
        "/_authenticated/storage/certificates",
        "/_authenticated/storage/cloud-stores",
        "/_authenticated/storage/sites",
        "/_authenticated/tools/audit",
        "/_authenticated/tools/graphql",
        "/_authenticated/$entity/",
        "/_authenticated/chats/",
        "/_authenticated/help-center/",
        "/_authenticated/users/",
        "/_authenticated/$entity/$referenceId/edit",
        "/_authenticated/$entity/$referenceId/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/display",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/_authenticated/config": {
      "filePath": "_authenticated/config.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/actions": {
      "filePath": "_authenticated/admin/actions.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/actions/$actionId"
      ]
    },
    "/_authenticated/admin/groups": {
      "filePath": "_authenticated/admin/groups.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/permissions": {
      "filePath": "_authenticated/admin/permissions.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/state-machines": {
      "filePath": "_authenticated/admin/state-machines.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/admin/state-machines/$smdId"
      ]
    },
    "/_authenticated/admin/users": {
      "filePath": "_authenticated/admin/users.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/communication/email": {
      "filePath": "_authenticated/communication/email.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/communication/oauth": {
      "filePath": "_authenticated/communication/oauth.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/communication/websocket": {
      "filePath": "_authenticated/communication/websocket.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/create/$entity": {
      "filePath": "_authenticated/create/$entity.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/exchanges": {
      "filePath": "_authenticated/data/exchanges.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/export": {
      "filePath": "_authenticated/data/export.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/import": {
      "filePath": "_authenticated/data/import.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/data/integrations": {
      "filePath": "_authenticated/data/integrations.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/data/integrations/$integrationId"
      ]
    },
    "/_authenticated/data/streams": {
      "filePath": "_authenticated/data/streams.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/storage/certificates": {
      "filePath": "_authenticated/storage/certificates.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/storage/cloud-stores": {
      "filePath": "_authenticated/storage/cloud-stores.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/storage/cloud-stores/$storeId"
      ]
    },
    "/_authenticated/storage/sites": {
      "filePath": "_authenticated/storage/sites.lazy.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/storage/sites/$siteId"
      ]
    },
    "/_authenticated/tools/audit": {
      "filePath": "_authenticated/tools/audit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/tools/graphql": {
      "filePath": "_authenticated/tools/graphql.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/$entity/": {
      "filePath": "_authenticated/$entity/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chats/": {
      "filePath": "_authenticated/chats/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.lazy.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/$entity/$referenceId/edit": {
      "filePath": "_authenticated/$entity/$referenceId/edit.lazy.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/admin/actions/$actionId": {
      "filePath": "_authenticated/admin/actions.$actionId.lazy.tsx",
      "parent": "/_authenticated/admin/actions"
    },
    "/_authenticated/admin/state-machines/$smdId": {
      "filePath": "_authenticated/admin/state-machines.$smdId.lazy.tsx",
      "parent": "/_authenticated/admin/state-machines"
    },
    "/_authenticated/data/integrations/$integrationId": {
      "filePath": "_authenticated/data/integrations.$integrationId.lazy.tsx",
      "parent": "/_authenticated/data/integrations"
    },
    "/_authenticated/storage/cloud-stores/$storeId": {
      "filePath": "_authenticated/storage/cloud-stores.$storeId.lazy.tsx",
      "parent": "/_authenticated/storage/cloud-stores"
    },
    "/_authenticated/storage/sites/$siteId": {
      "filePath": "_authenticated/storage/sites.$siteId.lazy.tsx",
      "parent": "/_authenticated/storage/sites"
    },
    "/_authenticated/$entity/$referenceId/": {
      "filePath": "_authenticated/$entity/$referenceId/index.lazy.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
